CREATE TABLE
    TRANSACTIONS
    (
        TRANSACTION_ID BIGINT NOT NULL,
        DATE DATETIME NOT NULL,
        DETAILS NVARCHAR(255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
        DETAILS_TYPE NVARCHAR(255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
        LOAN_ID NVARCHAR(20) COLLATE SQL_Latin1_General_CP1_CI_AS,
        TURNOVER DECIMAL(16,6),
        BALANCE DECIMAL(16,6),
        CURRENCY VARCHAR(3) COLLATE SQL_Latin1_General_CP1_CI_AS,
        EXCHANGE_RATE DECIMAL(16,6),
        PURPOSE NVARCHAR(255) COLLATE SQL_Latin1_General_CP1_CI_AS,
        PRIMARY KEY (TRANSACTION_ID),
        CONSTRAINT TRANSACTIONS_ix1 UNIQUE (TRANSACTION_ID)
    );
    
CREATE TABLE
    INVESTMENT
    (
        DATE DATETIME NOT NULL,
        INVESTMENT DECIMAL(18,6) NOT NULL
    );